name: aws_policy_expander_minimizer
description: >
  A library for expanding and minimizing AWS policies.
version: 0.0.1
#author: <Patrick Kelley> <pkelley@netflix.com> @monkeysecurity
#homepage: zsh.sh
dev_dependencies:
  unittest: any
